(defpackage #:axion.game-utils
  (:use :cl :alexandria :split-sequence :cl-heap)
  (:export *system*
           *executablep*
           :get-path
           :read-data
           :load-texture
           :image->texture
           :mouse-coords
           :unproject-vector
           :gl-get-id
           :gl-send-matrix
           :gl-draw-arrays
           :vec
           :vx
           :vy
           :vz
           :vcp
           :vcp*
           :vclr*
           :vlist
           :vneg
           :vneg*
           :vadd
           :vadd*
           :vsub
           :vsub*
           :vmult
           :vmult*
           :vscale
           :vscale*
           :vrev
           :vrev*
           :vlen
           :vnorm
           :vnorm*
           :vround
           :vround*
           :vpos
           :vpos*
           :vcross
           :vcross*
           :vdot
           :vbox
           :vdist
           :vtrans
           :vtrans*
           :vzerop
           :vclosep
           :vdirp
           :vparp
           :vnegp
           :mat
           :matcp
           :matcp*
           :matid
           :matid*
           :matstab
           :matstab*
           :matmult
           :matmult*
           :mattransp
           :mattransp*
           :matrot
           :matrot*
           :mattransl
           :mattransl*
           :matscale
           :matscale*
           :matrota
           :matrota*
           :matgettransl
           :matgettransl*
           :matcprot
           :matcprot*
           :matapply
           :matapply*
           :move-by
           :rotate-by
           :rpms->radians
           :vector-floats
           :get-rotation
           :set-direction
           :get-angle
           :line-direction
           :line-midpoint
           :project-plane
           :line-plane-intersect
           :point-line-distance
           :axial->cube
           :cube->axial
           :cube->hex
           :hex->cube
           :hex-distance
           :hex-round
           :hex-neighbor
           :hex-neighbors
           :hex-neighbors-p
           :load-obj
           :key-down
           :key-up
           :mouse-down
           :mouse-up
           :frame
           :step-frame
           :dt
           :accumulator))
